name: to_shunichi_prj
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  # ここにhttps://pub.devから引っ張ってきたパッケージをかく
  # 例：
  #    パッケージ名: パッケージのバージョン

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  flutter_state_notifier: ^0.7.1
  state_notifier: ^0.7.2+1
  freezed_annotation: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  freezed:
  json_serializable:

flutter:
  uses-material-design: true
